export const FETCH_PERSONS_ERROR = "FETCH_PERSONS_ERROR";
export const FETCH_PERSONS_LOADING = "FETCH_PERSONS_LOADING";
export const FETCH_PERSONS_SUCCESS = "FETCH_PERSONS_SUCCESS";

export const DELETE_PERSON_ERROR = "DELETE_PERSON_ERROR";
export const DELETE_PERSON_LOADING = "DELETE_PERSON_LOADING";
export const DELETE_PERSON_SUCCESS = "DELETE_PERSON_SUCCESS";

export const EDIT_PERSON_ERROR = "EDIT_PERSON_ERROR";
export const EDIT_PERSON_LOADING = "EDIT_PERSON_LOADING";
export const EDIT_PERSON_SUCCESS = "EDIT_PERSON_SUCCESS";

export const ADD_PERSON_LOADING = "ADD_PERSON_LOADING";
export const ADD_PERSON_ERROR = "ADD_PERSON_ERROR";
export const ADD_PERSON_SUCCESS = "ADD_PERSON_SUCCESS";
